import React, { useState } from "react";
import API from "../api/AxiosConfig";
import { Sparkles, Bot, Send, Globe } from "lucide-react";
import { toast } from "react-toastify";

const CreatePromptForm = ({ onPromptCreated }) => {
  const [loading, setLoading] = useState(false);
  const [aiLoading, setAiLoading] = useState(false);


  const [aiContent, setAiContent] = useState("");
  const [aiTitle, setAiTitle] = useState("");


  const handleAIAssist = () => {
    if (!aiTitle.trim()) {
      toast.warning("Pehle title likho, tabhi AI content generate karega!");
      return;
    }

    setAiLoading(true);

    setTimeout(() => {
      setAiContent(
        `Expert prompt structure for "${aiTitle}":\n\n1. Role: Act as an expert.\n2. Context: Provide accurate results.\n3. Output format: Clean and structured.`
      );
      setAiLoading(false);
      toast.success("AI generated content successfully!");
    }, 800);
  };


  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!aiTitle.trim() || !aiContent.trim()) {
      toast.warning("Title aur Content required hai!");
      return;
    }

    setLoading(true);

    const form = new FormData(e.target);

    const payload = {
      title: aiTitle, 
      content: aiContent,
      category: form.get("category"),
      isPublic: form.get("isPublic") === "on",
    };

    try {
      const response = await API.post("/api/prompts", payload, {
        withCredentials: true,
      });

      toast.success(response.data.message || "Prompt created successfully!");

      // Reset
      setAiContent("");
      setAiTitle("");
      e.target.reset();

      if (onPromptCreated) onPromptCreated();
    } catch (error) {
      console.error("Error creating prompt:", error);
      toast.error(error.response?.data?.message || "Failed to create prompt.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="bg-white rounded-3xl p-6 md:p-8 shadow-sm flex flex-col gap-6 w-full border border-gray-100">
      
      {/* Header */}
      <div className="flex justify-between items-center border-b pb-4">
        <div className="flex flex-col gap-1">
          <h3 className="text-xl font-bold text-[#203A3E] flex items-center gap-2">
            <Sparkles size={20} className="text-[#FF9E20]" />
            Create New Prompt
          </h3>
          <p className="text-xs text-gray-400">
            Tags will be automatically generated by AI based on your content.
          </p>
        </div>

        <button
          type="button"
          onClick={handleAIAssist}
          disabled={aiLoading}
          className="flex items-center gap-1.5 text-xs font-bold text-purple-600 bg-purple-50 px-4 py-2 rounded-xl hover:bg-purple-100 transition disabled:opacity-50"
        >
          <Bot size={16} />
          {aiLoading ? "Thinking..." : "AI Assist ✨"}
        </button>
      </div>

      {/* Form */}
      <form onSubmit={handleSubmit} className="flex flex-col gap-4">

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          
          {/* Title */}
          <div className="flex flex-col gap-1.5">
            <label className="text-xs font-bold text-gray-600">
              Title <span className="text-red-500">*</span>
            </label>
            <input
              type="text"
              name="title"
              placeholder="e.g. Instagram Reels Script Writer"
              value={aiTitle}
              onChange={(e) => setAiTitle(e.target.value)}
              className="bg-gray-100 h-12 rounded-xl px-4 text-sm font-medium outline-none focus:ring-2 focus:ring-[#FF9E20]"
              required
            />
          </div>

          {/* Category */}
          <div className="flex flex-col gap-1.5">
            <label className="text-xs font-bold text-gray-600">Category</label>
            <select
              name="category"
              defaultValue="Other"
              className="bg-gray-100 h-12 rounded-xl px-4 text-sm font-medium outline-none focus:ring-2 focus:ring-[#FF9E20]"
            >
              <option value="Fitness">Fitness</option>
              <option value="Motivation">Motivation</option>
              <option value="Marketing">Marketing</option>
              <option value="Coding">Coding</option>
              <option value="Design">Design</option>
              <option value="Writing">Writing</option>
              <option value="Instagram">Instagram</option>
              <option value="Other">Other</option>
            </select>
          </div>

        </div>

        {/* Content */}
        <div className="flex flex-col gap-1.5">
          <label className="text-xs font-bold text-gray-600">
            Content <span className="text-red-500">*</span>
          </label>
          <textarea
            name="content"
            rows={5}
            placeholder="Write your prompt content here..."
            value={aiContent}
            onChange={(e) => setAiContent(e.target.value)}
            className="bg-gray-100 rounded-xl p-4 text-sm font-medium outline-none focus:ring-2 focus:ring-[#FF9E20] resize-none min-h-[120px]"
            required
          />
        </div>

        {/* Footer */}
        <div className="flex flex-col md:flex-row justify-between items-center gap-4 pt-2">

          <label className="flex items-center gap-3 cursor-pointer bg-gray-50 px-4 py-3 rounded-xl border border-gray-200 w-full md:w-auto">
            <input
              type="checkbox"
              name="isPublic"
              className="w-4 h-4 accent-[#FF9E20]"
            />
            <div className="flex items-center gap-2 text-xs font-bold text-gray-700">
              <Globe size={16} className="text-gray-500" />
              <span>Make Public</span>
            </div>
          </label>

          <button
            type="submit"
            disabled={loading}
            className="h-12 w-full md:w-auto px-8 bg-[#FF9E20] text-white rounded-xl text-sm font-bold shadow-md hover:bg-[#e88d15] transition flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <Send size={16} />
            <span>{loading ? "Creating..." : "Save Prompt"}</span>
          </button>

        </div>
      </form>
    </div>
  );
};

export default CreatePromptForm;